# Étape 1 : Image légère Node.js
FROM node:20-alpine

# Étape 2 : Répertoire de travail
WORKDIR /app

# Étape 3 : Copier uniquement package.json pour installer dépendances
COPY package*.json ./

# Étape 4 : Installer dépendances
RUN npm install

# Étape 5 : Copier tout le code
COPY . .

# Étape 6 : Lancer nodemon pour le dev
CMD ["npx", "nodemon", "server.js"]
